export const mockPortfolio = [
  {
    symbol: "TCS",
    name: "Tata Consultancy Services",
    quantity: 10,
    avgPrice: 3200,
    currentPrice: 3350,
    pnl: 1500,
    pnlPercent: 4.69,
    allocation: 30.2,
  },
  {
    symbol: "INFY",
    name: "Infosys Ltd",
    quantity: 15,
    avgPrice: 1400,
    currentPrice: 1380,
    pnl: -300,
    pnlPercent: -1.43,
    allocation: 18.7,
  },
  {
    symbol: "HDFC",
    name: "HDFC Bank",
    quantity: 8,
    avgPrice: 1600,
    currentPrice: 1725,
    pnl: 1000,
    pnlPercent: 7.81,
    allocation: 17.9,
  },
  {
    symbol: "RELIANCE",
    name: "Reliance Industries",
    quantity: 5,
    avgPrice: 2800,
    currentPrice: 2950,
    pnl: 750,
    pnlPercent: 5.36,
    allocation: 15.1,
  },
  {
    symbol: "WIPRO",
    name: "Wipro Ltd",
    quantity: 20,
    avgPrice: 420,
    currentPrice: 395,
    pnl: -500,
    pnlPercent: -5.95,
    allocation: 9.6,
  },
  {
    symbol: "ICICIBANK",
    name: "ICICI Bank",
    quantity: 12,
    avgPrice: 950,
    currentPrice: 1010,
    pnl: 720,
    pnlPercent: 6.32,
    allocation: 8.5,
  },
];